### ISSUE TITLE
Forward & backward jumps with ConTEXt and SyncTeX.

### ISSUE THREAD

**Issue by vntex** [frabjous/knap#12] opened 2022-09-15 13:15 UTC
I have tried KNAP on Manjaro running NVIM v0.7.2 with [Hello-world.tex](https://wiki.contextgarden.net/images/2/22/Hello-world.tex)  retrieved from [ConTEXt Garden](https://wiki.contextgarden.net/Main_Page) with the following settings for KNAP.

   
  ```
    -- KNAP buffer settings
	local b_knap_settings = {
		texoutputext = "pdf",
		textopdf = "context --synctex --batchmode %docroot%",
		textopdfviewerrefresh = "kill -HUP %pid%",
	}
	vim.b.knap_settings = b_knap_settings
	map({ "i", "n", "v", "c" }, "<F6>", function()
		require("knap").close_viewer()
	end)
	-- F8 toggles the auto-processing on and off
	map({ "i", "n", "v", "c" }, "<F8>", function()
		require("knap").toggle_autopreviewing()
	end)
	-- F9 invokes a SyncTeX forward search, or similar, where appropriate
	map({ "i", "n", "v", "c" }, "<F9>", function()
		require("knap").forward_jump()
	end)
```
When the [routine] launched and Sioyek comes up, I change to cursor position in the source file then press F9, nothing seems to happen to the viewer. The inverse jumps don't work either when I am in Sioyek, press F4 then right click on one of the lines, only a message saying "jump spot at line 0 col 0 in" appears in the command window of Neovim.

ConTEXt also add a file hello-world.synctex after processing the source file. I don't know if it is relevant to add its content here.

When I run "pgrep -l sioyek", I have something like this:

`39136 sioyek --inverse-search nvim --headless -es --cmd "lua require('knaphelper').relayjump('/tmp/nvima4Gwtp/0','%1',%2,%3)" --reuse-instance hello-world.pdf
`
Another interesting thing that I have found is if I toggle autoviewing function (press F8) 3 times, then close_viewer() (press F6) will no longer work.

These things happen probably Sioyek does not respond to Neovim via Syntex on my system. LaTeX users might not experience above things. Honestly, I don't mind all of the issues I have with my setups, just wanted to test KNAP and dig into its code for learning.

I am very grateful to KNAP's author, who is very kind and generous in replying my report via email.

**Comment by frabjous** [comment] 2022-09-15 18:50
Thanks for the information. I have been able to duplicate the issue with SyncTeX using your settings.

From what I can tell, the issue seems to be something specific to ConTeXt. I don't think the fix would be something that could be done to or with the knap plugin, but I'm not sure. Sioyek doesn't seem to work with SyncTeX for ConTeXt files period, no matter how it's invoked. And I'm not sure it's Sioyek's fault either. I cannot get the `synctex` command line tool to work at all with ConTeXt.

I don't know ConTeXt very well; I've never really used it myself. (I only use pdflatex, xelatex or lualatex.) Googling doesn't turn up much, but some hints online (e.g., in the mailing list thread that starts [here](https://mailman.ntg.nl/pipermail/ntg-context/2019/094636.html)) make it sound as if changes to how SyncTeX works were never adapted for ConTeXt and special libraries need to be used to access its SyncTeX functions rather than the command line tool. (I'm not sure exactly how Sioyek invokes SyncTeX.)

I might post a question about it at the TeX, LaTeX and friends stackexchange site and see if anyone knows the current state of SyncTeX support for ConTeXt.

I'm still thinking about the issue with toggling the preview on or off, and will update here if I think of a good way to address it.

**Comment by frabjous** [comment] 2022-09-16 01:48
Update.

If I am reading [this mailing list discussion](https://www.mail-archive.com/ntg-context@ntg.nl/msg98423.html) right, ConTeXt has a completely separate implementation from the usual implementation of SyncTeX. I guess TeXShop has some builtin support for this alternative version.

You might be able to write a script that parses the output of the `mtxrun` script mentioned in the mailing list and make use of Sioyek's `--page`, `--xloc` and `--yloc` options instead of its `--forward-search-file` and `--forward-search-line` options to hack together a forward jump from source to output. (Then you could change the `textopdfforwardjump` in knap to make use of it.)

Backward jumps from output to source would require changes to Sioyek itself, so that if configured to do so, it would use this alternative implementation rather than the standard SyncTeX library and tools. You could post a suggestion on its bug tracker, but I wouldn't hold my breath.

Anyway, not much I can do about this for knap; not by myself anyway. I'm not even a ConTeXt user.

As for the preview toggling, and this making close_viewer no longer close Sioyek, after some experimentation, I *think* is is actually caused by this line in your configuration:

```
textopdfviewerrefresh = "kill -HUP %pid%",
```

This is ending the shell process through which Sioyek is launched, so that Sioyek itself gets orphaned, and no longer has that shell process as its parent. So it is not killed when `pkill -P [pid]` is run on the parent's pid.

I'm not sure why you have that setting there. I know there are similar refresh commands in the README suggested for things like `mupdf` and `llpp`, but those programs trap the signal and use it as a trigger to refresh, since they don't auto-refresh.

Sioyek auto-refreshes when the file being viewed changes, so this shouldn't be necessary. In fact, if you send the HUP signal to the actual Sioyek process rather than its parent, it closes Sioyek, which is the last thing you want a refresh command to do.

If I were you, I'd set it back to:
```
textopdfviewerrefresh = "none"
```
(Or you can just leave that line out, since it's the default.)

This appears to be a separate issue from the one I mentioned in my email, i.e., that if Sioyek is already open when the preview is first launched by knap, then it also cannot be closed by knap either, since it still has its original pid, not one derived by the shell knap launches. But, arguably, how it should be: the plugin shouldn't be able to close windows it didn't create. 

(Though I guess you could change the close command from `pkill -P` to `killall sioyek` or something similar if you wanted to be *very* forceful about it, but I wouldn't recommend it.)

**Comment by vntex** [comment] 2022-09-16 02:27
Thank you for a very clear addressing the problems I have with my setups.

Commenting out the line `textopdfviewerrefresh = "kill -HUP %pid%"` does eliminate the effect of double-previewing on close_viewer(). I did not have that line initially, then found out the SyncTEX does not work, I came back and turned the viewerrefresh on to see if it would help. This turned out with the double-previewing.
I will do some research with SyncTEX for ConTEXt's side to see if I can make it work.

**Comment by vntex** [comment] 2022-09-16 02:58
After reading the mailing list you pointed out previously, from my understanding that if one could come up with a script parsing the content of `.synctex` file then feed the info of `--page, --x, --y` to the viewer and editor, this would solve the backward - forward jumping story with ConTEXt.

**Comment by frabjous** [comment] 2022-09-16 14:44
Yes, that's what I had in mind you could try for forward jumps. The mtxrun script's output may be easier to parse than the .synctex file directly, but I'm not sure, as I haven't tried.

For backward jumps, while you could probably write a script that turned page coordinates in to line numbers, and invoked my knaphelper script to make neovim move its cursor to the appropriate spot (which I can help with if it's not clear), but there's still going to be the problem of how to make Sioyek invoke your script. As far as I know, what Sioyek does when someone right clicks on a page in its synctex mode is not easily configurable short of changing the source code. But maybe you have an idea that isn't occurring to me.

**Comment by vntex** [comment] 2022-10-05 09:01
Dear sir,

After some [research](https://tex.stackexchange.com/questions/480753/how-does-synctex-work) and some time studying your code, I was able to extract line numbers from the `.synctex` with the chunk bellow:

```
-- textopdflistsynctex = "mtxrun --script synctex --list %%synctex%%"
-- where %%synctex%% = vim.b.knap_docroot:gsub('%.[^%.]*$', '.' .. 'synctex')
local synctex_cmd = vim.b.knap_settings[vim.b.knap_routine .. "listsynctex"]
synctex_cmd = fill_in_cmd(synctex_cmd)
line_numbers = {}
-- for line in io.popen(synctex_cmd):lines() do
for line_num in line:gmatch("%d+%s*:") do
        local num = line_num:gsub('%s*:', '')
        table.insert(line_numbers, tonumber(num))
    end
end
```
I guess that we could keep the value of `column` to be 0 while working on the `line` numbers, which can be piped to the `jump()` function, knowing that we've already had the info of `srcfile` and `ouputfile`. However, I haven't got a clue how to do that. The structure of `.synctex` generated by ConTEXt looks very different from what `pdflatex` produces, and when listed with `mtxrun` script, the first page is always skipped. `.synctex` ouput from compiling `.mkiv` has very little content with no information about `line`.

While learning your code, I realised that we could use [vim.v.echospace](https://github.com/neovim/neovim/issues/16462) in the place of:

```
-- determine maximum width of messages
local ffi=require('ffi')
ffi.cdef('int sc_col;')
local knap_max_col_width = (ffi.C.sc_col - 1)
```
for 
```
function err_msg(msg)
    api.nvim_echo({{msg:sub(1, knap_max_col_width), 'ErrorMsg'}}, true, {})
    -- api.nvim_echo({{msg:sub(1, vim.v.echospace), 'ErrorMsg'}}, true, {})
end
```
I'm still having problem with compiling TEX file using context, as you know rubber-info doesn't support ConTEXt syntax, I've changed my knap_settings as bellow:

```
local function knap_context_or_tex()
		local ft = vim.opt_local.filetype:get()
		if ft == "context" then
			return {
				textopdf = "mtxrun --autogenerate --script context --batchmode %docroot%",
        			textopdfshorterror = "A=%outputfile% ; LOGFILE=\"${A%.pdf}.log\" ; mtxrun --script mtx-check --check \"$LOGFILE\" 2>&1 | head -n 1",
				mkivoutputext = "pdf",
				mkivtopdf = "mtxrun --autogenerate --script context --batchmode %docroot%",
				-- mkivtopdf = "~/.context-lmtx/bin/mtxrun --script context --batchmode %docroot%",
				mkivtopdfviewerlaunch = "sioyek --inverse-search 'nvim --headless -es --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' --reuse-instance %outputfile%",
				mkivtopdfforwardjump = "sioyek --inverse-search 'nvim --headless -es --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' --reuse-instance --forward-search-file %srcfile% --forward-search-line %line% %outputfile%",
				mkivlistsynctex = "mtxrun --script synctex --list %synctex% ",
        			-- mkivtopdfshorterror = "none",
			}
		end
	vim.b.knap_settings = knap_context_or_tex()
```
The ERR message still shows up when I press F5 (process_once()), even when I change the `textopdfshorterror` to "none'. I know that the `exitcode` is not 0, so the main `else` part of `on_exit()` is executed.

```
            ...
            local errproc = io.popen(shorterrcmd)
            local errmsg = vim.trim(errproc:read("*a"))
            errproc:close()
            err_msg('ERR: ' .. errmsg)
            ...
```
If I comment out this `else` part, I will have the ERR message showing wrong syntax from `            err_msg('ERR: ' .. vim.b.knap_process_stderr)` in the main `if` part of `on_exit()`. If I change the default setting in `knap.lua` for `textopdfshorterror` to 'none', then source file then is not compiled. However, this does not happen when I run KNAP with `.mkiv` files.
I've looked into the code of `on_stderr ()` but still have no clue about its logic and where the argument `data`, which is a table, is used. Obviously, the error report does not produced by this function.

It would be very grateful if you could share your thought about disabling error reporting on ConTEXt syntax. TEX files in ConTEXt synctax run smoothly in zsh shell. If you have Texlive installed, contex is shipped with it, and you could test this [Hello-world.tex](https://wiki.contextgarden.net/images/2/22/Hello-world.tex).

Thank you for your valuable time looking into this.

**Comment by vntex** [comment] 2022-10-05 13:18
I have managed to solve the TEX files compiling problem with context by declaring the knap's settings directly (`vim.b.knap_settings = b_knap_settings`) instead of enclosing them in a local function. The ERR reporting mechanism also works with `mtxrun` script.

**Comment by frabjous** [comment] 2022-10-06 01:43
> After some [research](https://tex.stackexchange.com/questions/480753/how-does-synctex-work) and some time studying your code, I was able to extract line numbers from the `.synctex` with the chunk bellow:

I'm not sure what good a list of line numbers by itself does. You need at least to keep track of which line numbers came from which page. If you have both of those, it might be possible to get a rough forward search to work, accurate only to the page number. But I wouldn't define a function for that in `knap.lua`: I'd probably create a separate script to which you passed the filename and line number and set that script as the value of `textopdfforwardjump` and `mkivtopdfforwardjump`.

> I guess that we could keep the value of `column` to be 0 while working on the `line` numbers, which can be piped to the `jump()` function, knowing that we've already had the info of `srcfile` and `ouputfile`. 

The `jump()` function is for reverse searches, but I still don't understand how they could work with Sioyek. The `--inverse-search` option to Sioyek fills in `%1`, `%2` and `%3` in its argument by invoking the regular version of synctex. If the output file doesn't have a regular `.synctex.gz` file, you'll get a blank string for `%1` and 0 for for `%2` and `%3`. The column isn't really important: even (current versions of) regular synctex always outputs a 0 there, but `%2` for the line number corresponding to where was clicked was essential. You could write your own script for finding the right page number if could get the page number and click coordinates, but Sioyek doesn't have a way to communicate those, as far as I can see.

There might be a way with llpp, but that's a different can of worms to open.

However, I haven't got a clue how to do that. The structure of `.synctex` generated by ConTEXt looks very different from what `pdflatex` produces, and when listed with `mtxrun` script, 

> the first page is always skipped. 

That's extremely strange, and I don't see how it could be considered anything but a bug with ConTeXt/mtxrun. You might report it to their devs.


> While learning your code, I realised that we could use [vim.v.echospace](https://github.com/neovim/neovim/issues/16462) ...

Thanks. I didn't know about that variable. That's definitely cleaner. I'll switch to using that.

> The ERR message still shows up when I press F5 (process_once()), even when I change the `textopdfshorterror` to "none'. 

My thought was that if you set that to "none", it should do the same thing as if it wasn't set at all, i.e., output what it can from stderr, but I can see some use cases where you might not want that either. I've changed the code now so that you just get a generic error message reporting the exit code if it's set to "none".

My intention though was to encourage people to use this setting to insert a command that parses log files, which I gather from your other post you were able to get working after changing how you set the initial variables.

> If I change the default setting in `knap.lua` for `textopdfshorterror` to 'none', then source file then is not compiled. 

I don't see how changing that setting could have any effect on compilation, but maybe the issue is related to the way you were determining the settings.

> I've looked into the code of `on_stderr ()` but still have no clue about its logic and where the argument `data`, which is a table, is used. Obviously, the error report does not produced by this function.

The data just consists of chunks of output from the standard error stream of the process (error messages it spits out to the command line when run). The only place I use this is when the shorterror option for the routine is not set. I mainly use that for other routines. Programs like pandoc usually don't produce a log file but do output short and informative error messages to stderr when they encounter errors.

From what I can tell, context spits its errors to stdout rather than stderr which is sloppy programming, but it does produce a log file, so it's far better to parse the log if you can.

> I have managed to solve the TEX files compiling problem with context by declaring the knap's settings directly (vim.b.knap_settings = b_knap_settings) instead of enclosing them in a local function

I don't know exactly what the restrictions are, but since variables in `vim.b` are really `b:` vimscript variables, not lua variables, it does lua-to-vim conversion when you set one in lua, and it's very fussy about how you do that. I know for example, that you can't directly do `vim.b.knap_settings["..."] = ...` like you could with a normal lua table, which would have been handy. It might be that you can't directly set it with a function's return value either for some reason. 

Anyway if you want to be able to have different settings for `textopdf...` routines automatically set depending on whether `ft=tex` or `ft=context`, it might be better to do that with just a conditional clause, or put the settings in a ftplugin for load them with an autocmd.

**Comment by vntex** [comment] 2022-10-06 08:17
Thank you for your quick and detailed response!

> I'm not sure what good a list of line numbers by itself does. You need at least to keep track of which line numbers came from which page. If you have both of those, it might be possible to get a rough forward search to work, accurate only to the page number. 

It not simple as I thought. First, I saw your code for `textopdfforwardjump`, in theory, the only argument `%line%` would be provided to it then the problem would be solved. But in reality, `sioyek` needs more than that, the based parameter `%line%` is probably used to parse the `.synctex` file for page coordinates. I added this bit to `fill_in_cmd(cmd)`, but it does not work for context while latex files are not affected (latex files work as they supposed to).
```
-- replace %fields% in cmd with values
local pos = api.nvim_win_get_cursor(0)
local row, col = pos[1], pos[2]
local synctex_cmd = "mtxrun --script synctex --list " .. vim.b.knap_docroot:gsub('%.[^%.]*$', '.synctex')
local line_numbers = {}
-- for line in io.popen(synctex_cmd):lines() do
for line in io.popen(synctex_cmd):lines() do
	for line_num in line:gmatch("%d+%s*:") do
		local num = line_num:gsub("%s*:", "")
		table.insert(line_numbers, num)
	end
end
table.sort(line_numbers)
for _, v in ipairs(line_numbers) do
    if row == v then
        row = v
    else
	row = row
    end
end
```

> From what I can tell, context spits its errors to stdout rather than stderr which is sloppy programming, but it does produce a log file, so it's far better to parse the log if you can.

ConTEXt does provide a mechanism for parsing the log file:
`textopdfshorterror = 'A=%outputfile% ; LOGFILE="${A%.pdf}.log" ; mtxrun --script mtx-check --check "$LOGFILE" 2>&1 | head -n 1'`
This works smoothly as expected.

> Anyway if you want to be able to have different settings for textopdf... routines automatically set depending on whether ft=tex or ft=context, it might be better to do that with just a conditional clause, or put the settings in a ftplugin for load them with an autocmd.

Conditional statements don't work for `filetype`, and followed your suggestion, I've got it work with autocmd. Thank you again for this. The chunk bellow might be useful for those who wish to switch between ConTEXt and LaTEX seamlessly with KNAP.

```
local knap_context_settings
function knap_context_settings()
        local bufnr = vim.api.nvim_get_current_buf()
	local ft = vim.api.nvim_buf_get_option(bufnr, "filetype")
	local context_knap_settings = {
		textopdf = "mtxrun --autogenerate --script context --batchmode %docroot%",
		...
	}
	if ft == "context" then
		vim.b.knap_settings = context_knap_settings
	end
end
vim.api.nvim_create_autocmd({ "FileType" }, {
	pattern = { "context" },
	callback = function()
		vim.schedule(knap_context_settings)
	end,
})
```
In the end, I may have to accept that SyncTEX does not work for ConTEXt though.

**Comment by frabjous** [comment] 2022-10-06 20:59
> It not simple as I thought. First, I saw your code for `textopdfforwardjump`, in theory, the only argument `%line%` would be provided to it then the problem would be solved. But in reality, `sioyek` needs more than that, the based parameter `%line%` is probably used to parse the `.synctex` file for page coordinates. I added this bit to `fill_in_cmd(cmd)`, but it does not work for context while latex files are not affected (latex files work as they supposed to).

I think it won't be possible to do it at all by making use of Sioyek's `--forward-search-file` `--forward-search-line` and `--forward-search-column` options. Sioyek is, as far as I know, hard-coded to use "normal" synctex to determine where those correspond to in the PDF, and so they won't work with a ConTeXt-generated `.synctex` file.

Instead of anything like my relatively simple default `textopdfforwardjump` command, you'd have to make use of an intervening script as the value of `XXXforwardjump` in knap, and pass it the source filename, line number and column. The script would then do whatever it needs to do with the `.synctex` file to figure out where in the PDF matches, and then call Sioyek invoking its `--page` option (and also the `--xloc` and `--yloc` options if you can figure out those details too) to open at the right spot.

You probably won't get highlighting, but I don't particularly find the highlighting to be the important thing.
 
 
> Conditional statements don't work for `filetype`, and followed your suggestion, I've got it work with autocmd. Thank you again for this. 

I'd be surprised if it were completely impossible to do it conditionally, but the important thing is that you got it working.
 
> In the end, I may have to accept that SyncTEX does not work for ConTEXt though.

Even if it's theoretically possible, it may not be worth the effort. I don't know your use case though, so I think it's up to you whether or not you want to put the work into it.

**Comment by vntex** [comment] 2022-10-07 04:38
> I think it won't be possible to do it at all by making use of Sioyek's --forward-search-file --forward-search-line and --forward-search-column options. Sioyek is, as far as I know, hard-coded to use "normal" synctex to determine where those correspond to in the PDF, and that won't work with a ConTeXt-generated .synctex file.

I can't agree more with you on this point. Sioyek definitely digs into "normal" `.synctex` file. If it only relies those options you pointed out above, then solution will be simple. I'm looking into [mtx-synctex.lua](https://source.contextgarden.net/scripts/context/lua/mtx-synctex.lua) to see if I can get the ConTEXt's logic out.

>I'd be surprised if it were completely impossible to do it conditionally, but the important thing is that you got it working.

Several tries and it still doesn't work, I though simple logic of IF's would solve the problem, I had to use autocmd for the last resource.

> Even if it's theoretically possible, it may not be worth the effort. I don't know your use case though, so I think it's up to you whether or not you want to put the work into it.

You are right. Having SyncTEX is a nice thing, but people can live without it. I like programming even I'm not good at it and the logic behind. Beside working in another field with not much free time left, I still want to play around with TEX and Lua for fun to keep my mind going. Surfing around the internet and found your code fascinating, that was why I'm here. I must thank you for all your generous time and patience. 

I did not intent to pollute knap's code but eventually ended up changing a few places to fit my habit of working with TEX files. I've managed to launch viewer without having the routine processed and close the viewer smoothly when I accidentally launch it twice or even more. I will put the bits that I have changed bellow in case that someone would like to have the same features.

For `close_viewer()`:

```
function close_viewer()
	if not vim.b.knap_buffer_initialized then
		buffer_init()
	end
	-- trim any leading or trailing spaces around the viewer's name found in the
	-- vim.b.knap_viewer_launched_cmd, leaving the viewer's name to stand out.
	local viewername = vim.b.knap_viewer_launch_cmd:gsub(".*;%s*", ""):gsub(".*&&%s*", ""):gsub("%s.*$", "")

	-- check to see if the procname is still active, if it is, running will be true.
	local running = os.execute('pgrep "' .. viewername .. '" > /dev/null 2>&1')
	if vim.b.knap_viewerpid and (is_running(vim.b.knap_viewerpid)) then
		local waskilled = os.execute("pkill -P " .. tostring(vim.b.knap_viewerpid) .. " > /dev/null 2>&1")
		if waskilled == 0 then
			print("Viewer has been closed... ")
		else
			if running == 0 then
				-- referenced from: https://stackoverflow.com/questions/8987037/how-to-kill-all-pro
				local forced_kill = os.execute(
					"ps -ef | grep "
						.. "'"
						.. viewername
						.. "'"
						.. " | grep -v grep | awk '{print $2}' | xargs -r kill -9 > /dev/null 2>&1"
				)
				if forced_kill == 0 then
					print("Viewer has been closed... ")
				else
					-- above returns exit code of kill command
					err_msg("Could not kill process " .. tostring(vim.b.knap_viewerpid))
				end
			end
		end
	else
		if running == 0 then
			local forced_killed = os.execute(
				"ps -ef | grep "
					.. "'"
					.. viewername
					.. "'"
					.. " | grep -v grep | awk '{print $2}' | xargs -r kill -9 > /dev/null 2>&1"
			)
			if forced_killed == 0 then
				print("Viewer has been closed... ")
			else
				-- above returns exit code of kill command
				err_msg("Could not kill process " .. tostring(vim.b.knap_viewerpid))
			end
		end
	end
	-- mark viewer closed and stop autopreviewing if on
	mark_viewer_closed()
	stop_autopreviewing(true)
end
```
and for `launch_viewer()` (of course, we have to return it at the end of `knap.lua`)

```
        -- set viewer_launch_cmd if it has not been set. Obviously, the routine would not be defined
	-- if the input file has not been procecssed. The function launch_viewer() is designed to be
	-- triggered internally after a routine is set. The bellow small modification allows the user 
        -- to launch_viewer() without processing the source file for the case that he/she would like   
        -- to see the result from last session or the current one.
	-- if viewer launch command is triggered in the buffer with wrong filetype,
	-- or no output file is found; a warning message is displayed.
	if not vim.b.knap_settings or not (get_outputfile()) then
		err_msg("No output file or settings associated with the source file is found. No viewer launched!")
		return
	end
	-- If the viewer command has not been set.
	if not vim.b.knap_viewer_launch_cmd then
		set_variables()
	end
```

**Comment by vntex** [comment] 2022-10-10 01:28
Another small function may be worth adding to KNAP.

```
function clean_auxfiles()
	-- This function is designed for external call, so set_variables()
	-- should be called in advance to determine the auxiliary
	-- files' extension names and their location (e.g., in the same
	-- directory with the docroot.
	-- initialize if need be
	if not vim.b.knap_buffer_initialized then
		buffer_init()
	end
	-- Set variables if not previously done.
	if not set_variables() then
		set_variables()
	end
	-- Check for the existence of auxiliary files.
	-- source: https://www.tutorialspoint.com/how-to-use-lua-programming-to-check-if-a-file-exists
	local isFile = function(aux)
		local file = io.open(aux)
		if file ~= nil then io.close(file) return true else return false end
	end
	-- Define auxiliary files' extensions.
	local aux_exts = {'.aux', '.bbl', '.blg', '.fls', '.log', '.tuc'}
	for _, ext in pairs(aux_exts) do
		local aux_file = vim.b.knap_docroot:gsub('%.[^%.]*$', ext)
		if isFile(aux_file) then
			local aux_removed = os.remove(aux_file)
			if aux_removed then
				print("Removed: " .. aux_file)
			end
		end
	end
end

```

**Comment by frabjous** [comment] 2022-10-10 13:22
I have a function that essentially does that in my personal `~/.config/nvim/ftplugin/tex/tex.lua` plugin. I don't include it in knap because I subscribe to the unix philosophy: pieces of software should be modular: stick only to doing one task well.

The goal of the plugin is to handle auto-previewing alone, not be a all-encompassing plugin for LaTeX/ConTeXt files, much less one for all the different filetypes it could in principle handle. As much as possible, I'd like to keep the main code (apart from the defaults which are mainly there to provide an example) free of things specific to one filetype or use case.

My own tex ftplugin also handles things like smart punctuation, inserting bibtex references, fuller log parsing and jumping to the spot of errors, opening associated documentation with texdoc, an so on. But all of this is beyond what knap aims to do (or I aim to maintain!)

I'd also like to try to keep the code presuppose as little as possible about the OS and what tools are available, such as things specific to the GNU coreutils or any given shell. I realize, however, that I've probably already deviated from that more than I would like.

However, if there are changes you'd like to make which are not just for your own personal use case but you think would benefit all or nearly all others, please put them in a pull request to make things easier on both of us.

**Comment by vntex** [comment] 2022-10-11 09:28
I can't agree more, I see the intention, simplicity and logic in your code. I thought about pulling a request, but after learning about the features that VimTeX offers, I see your points even more clearly. Obviously, you wouldn't take KNAP down that road.

From time to time, I find many wonderful tips & tricks by skimming through open and closed issues on GitHub, including all the closed issues about KNAP as well. What I've put up there might be useful for someone who looks for the same things, I know not many out there and isn't an appropriate place to mention about unrelated matters. 

Thank you for your valuable time once again, sir.

**Closed** 2022-10-12 02:18 UTC
